render: Update files only if something other than creation date changed
This is possibly a little fragile and likely could use more testing.

diff --git a/render b/render
--- a/render
+++ b/render
@@ -2,6 +2,11 @@
 #
 #   render - Generate PDF schematics and Gerber PCB layouts
 #
+#   This takes .kicad_sch and .kicad_pcb files as parameters. It updates
+#   the rendered files only if they differ in something other than the
+#   creation date so that spurious changes are not generated in Git
+#   commits.
+#
 set -Eeuo pipefail
 trap 'ec=$?; echo 1>&2 "INTERNAL ERROR: ec=$ec line=$LINENO cmd=$BASH_COMMAND";
       exit $ec;' ERR
@@ -11,7 +16,50 @@ trap 'ec=$?; echo 1>&2 "INTERNAL ERROR: ec=$ec line=$LINENO cmd=$BASH_COMMAND";
 #   (Bash sorts glob/pathname expansions using LC_COLLATE.)
 export LC_COLLATE=C
 
-die() { ec=$1; shift; echo 1>&2 "$@"; exit $ec; }
+projdir=$(builtin cd "$(dirname "$0")" && pwd -P)
+render_tmp="$projdir/.build/tmp/render"
+
+####################################################################
+#   Support functions
+
+die() { ec=$1; shift; echo 1>&2 "$(basename "$0"):" "$@"; exit $ec; }
+
+clear_render_tmp() {
+    rm -rf "$render_tmp"
+    mkdir -p "$render_tmp"
+}
+
+#   The first two arges are source and target dirs; the remainder are
+#   regexps (pass these single-quoted). Each file in the source dir will be
+#   compared against a file of the same name in the target dir and, if
+#   there are any differences that are not ignored by the regexps, the
+#   source file will be copied over the target file. (If the target file
+#   does not exist, the copy will always be done.)
+copy_nonignored_diff() {
+    local sourcedir="$1"; shift
+    local targetdir="$1"; shift
+    #   Remaining args are `git --ignore-matching-lines` patterns.
+    local sourcefile targetfile
+
+    echo "Output directory: $targetdir/"
+    mkdir -p "$targetdir"
+    for sourcefile in "$sourcedir"/*; do
+        targetfile="$outdir/$(basename "$sourcefile")"
+        #   The -a is required for this to work with files that `git diff`
+        #   thinks are binary, even though we don't show output.
+        if    ! [[ -e $targetfile ]] \
+           || ! git diff -a --no-index --output=/dev/null \
+                "$sourcefile" "$targetfile" \
+                "${@/#/--ignore-matching-lines=}"
+        then
+            echo "Updating $(basename "$targetfile")"
+            cp "$sourcefile" "$targetfile"
+        fi
+    done
+}
+
+####################################################################
+#   Rendering functions
 
 render_sch() {
     local path="$1"; shift
@@ -19,46 +67,38 @@ render_sch() {
     local name=$(basename "$path" .kicad_sch)
     local srcdir=$(dirname "$path")
     local outdir="$srcdir"/../render
-    local output="$outdir/$name-sch.pdf"
-    mkdir -p "$outdir"
-    kicad-cli sch export pdf --output "$output" "$path"
 
-    #   XXX The above leaves the creation date in the file, which means
-    #   it will be changed every time the script is run. Previously we
-    #   modified the file as follows to get rid of it:
-    #
-    #       sed -i -e '/^\/CreationDate (D:..............)$/d' \
-    #           "$projdir/render/$basename-sch.pdf"
-    #
-    #   However, a better way to do this (that will preserve the original
-    #   creation date and be easier for the Gerbers as well) is simply to
-    #   generate the new version, diff with the last-committed
-    #   version, and copy the new version over the last-committed version
-    #   only if the diffs do not conisist entirely of lines containing
-    #   "CreationDate" or whatever. (But we need to note that we rely on
-    #   `kicad-cli sch export pdf` putting the CreationDate on a separate
-    #   line of the PDF, which it happens to do, but is not required for
-    #   the PDF format.)
+    clear_render_tmp
+    kicad-cli sch export pdf --output "$render_tmp/$name-sch.pdf" "$path"
+    copy_nonignored_diff "$render_tmp" "$outdir" \
+        '^/CreationDate \(D:..............\)$' \
+        #
 }
 
 render_pcb() {
-    #   XXX This currently overwrites all the output files with new
-    #   versions even if only the creation date of these files is changing.
     local path="$1"; shift
     echo "───── Rendering $(basename "$path")"
     pcbname=$(basename "$path" .kicad_pcb)
     local srcdir=$(dirname "$path")
     local outdir="$srcdir/../render/$pcbname-gerber"
 
-    echo "Output directory: $outdir/"
-    mkdir -p "$outdir"
+    clear_render_tmp
+
     #   Generates all layers, whether needed or not.
-    kicad-cli pcb export gerbers --output "$outdir" "$path"
+    kicad-cli pcb export gerbers --output "$render_tmp" "$path"
     #   The KiCad defaults match what JLCPCB asks for, excepting that
     #   JLCPCB suggests adding GerberX2 drill maps in as well.
     kicad-cli pcb export drill \
         --generate-map --map-format gerberx2 \
-        --output "$outdir" "$path"
+        --output "$render_tmp" "$path"
+    copy_nonignored_diff "$render_tmp" "$outdir" \
+        '^%TF\.CreationDate,20' \
+        '^G04 Created by KiCad .* date 20' \
+        '^    "CreationDate": "20' \
+        '^; DRILL file \{.*\} date 20' \
+        '^; #@! TF\.CreationDate,20' \
+        #
+
     #   Build ZIP files for submission to fabs.
     jlcpcb_zip "$pcbname" "$outdir"
 }
@@ -86,6 +126,7 @@ jlcpcb_zip() {
 ####################################################################
 #   Main
 
+git --version >/dev/null || die 3 'git command not found'
 kicad-cli --version >/dev/null || die 3 "kicad-cli command not found"
 strip-nondeterminism -V >/dev/null || die 3 "strip-nondeterminism command" \
     "not found; install strip-nondeterminism package?"
